// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://triyoequwkgmlxeffogv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaXlvZXF1d2tnbWx4ZWZmb2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMjEyMjUsImV4cCI6MjA1MTY5NzIyNX0.bgFkvywiPWlZSfGj4A_W4cDVoqWA7PYlGIQA_r3FpbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);